/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all active services */
        get: operations["getServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{serviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific service */
        get: operations["getService"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create-subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a PayPal subscription
         * @description Initiates a PayPal subscription for a user and service
         */
        post: operations["createSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activate-subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate a subscription after PayPal approval */
        post: operations["activateSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paypal-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle PayPal webhook events
         * @description Processes PayPal subscription lifecycle events
         */
        post: operations["handlePaypalWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/subscription-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user subscription status
         * @description Returns user's subscription status for all services. Used by desktop app for license validation.
         */
        get: operations["getSubscriptionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create or update a service
         * @description Admin only. Creates a new service or updates existing one.
         */
        post: operations["createOrUpdateService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/services/{serviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a service
         * @description Admin only. Permanently deletes a service.
         */
        delete: operations["deleteService"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/manual-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process a manual payment
         * @description Admin only. Records a manual payment and activates subscription.
         */
        post: operations["processManualPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/manual-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all manual transactions
         * @description Admin only. Returns all manual transactions with optional filters.
         */
        get: operations["getAllTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/manual-transactions/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user's manual transactions
         * @description Admin only. Returns manual transactions for a specific user.
         */
        get: operations["getUserTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/cancel-subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a user's subscription
         * @description Admin only. Cancels PayPal subscription and updates status.
         */
        post: operations["adminCancelSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/manage-group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manage Google Group membership
         * @description Admin only. Add or remove user from service's Google Group.
         */
        post: operations["manageGoogleGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/migrate-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Migrate users to multi-service schema
         * @description Admin only. One-time migration endpoint.
         */
        post: operations["migrateUsers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/seed-services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed initial services
         * @description Admin only. One-time endpoint to seed services collection.
         */
        post: operations["seedServices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transliterate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transliterate Hebrew media names to English
         * @description Transliterates song, artist, and album names from Hebrew to English.
         *     Uses OpenAI for intelligent transliteration that preserves meaning.
         *     Requires user authentication.
         */
        post: operations["transliterateMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata/spotify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Spotify track metadata
         * @description Extracts complete track metadata from a Spotify URL including:
         *     - Artist name
         *     - Track title
         *     - Album name
         *     - ISRC (International Standard Recording Code)
         *     - Duration (milliseconds)
         *     - Release date
         *     - Cover art URL
         *
         *     Uses Spotify's public embed page to obtain an anonymous access token,
         *     then calls the Spotify API for complete metadata. No authentication required.
         */
        post: operations["getSpotifyMetadata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata/spotify/album": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Spotify album metadata with all tracks
         * @description Extracts complete album metadata including all tracks with ISRCs.
         *     Returns album information and a list of all tracks with their metadata.
         *
         *     **Batch Processing:**
         *     - Fetches up to 50 tracks in a single API call
         *     - Each track includes ISRC for Deezer matching
         *     - Ideal for album/playlist downloads
         *
         *     Uses Spotify's public embed page to obtain an anonymous access token,
         *     then calls the Spotify API. No authentication required.
         */
        post: operations["getSpotifyAlbumMetadata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata/spotify/playlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Spotify playlist metadata with all tracks
         * @description Extracts complete playlist metadata including all tracks with ISRCs.
         *     Returns playlist information and a list of all tracks with their metadata.
         *
         *     **Batch Processing:**
         *     - Fetches up to 100 tracks per request
         *     - Each track includes ISRC for Deezer matching
         *     - Handles large playlists efficiently
         *
         *     Uses Spotify's public embed page to obtain an anonymous access token,
         *     then calls the Spotify API. No authentication required.
         */
        post: operations["getSpotifyPlaylistMetadata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download/deezer/isrc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Deezer download URL from ISRC
         * @description Retrieves a direct download URL for a track from Deezer using its ISRC code.
         *     Returns an encrypted MP3 download link that can be used to download the track.
         *
         *     **Quality Options:**
         *     - `MP3_128` - 128 kbps MP3
         *     - `MP3_320` - 320 kbps MP3 (default)
         *     - `FLAC` - Lossless FLAC audio
         *
         *     **Authentication:** Requires active `hasod-downloader` subscription.
         */
        post: operations["getDeezerDownloadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
            code?: string;
            message?: string;
        };
        SuccessResponse: {
            /** @constant */
            success: true;
            message: string;
        };
        Service: {
            /**
             * @example music-library
             * @example hasod-downloader
             */
            id: string;
            /** @example Music Library Access */
            name: string;
            /** @example גישה לספריית המוזיקה */
            nameHe: string;
            description: string;
            descriptionHe: string;
            /** @example P-4TS05390XU019010LNAY3XOI */
            paypalPlanId: string;
            /** @example 10 */
            pricePerMonth: number;
            /** @enum {string} */
            currency: "USD" | "ILS";
            /** Format: email */
            googleGroupEmail?: string;
            active: boolean;
            order: number;
            features: string[];
            featuresHe: string[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: string;
        };
        ServicesResponse: {
            services: components["schemas"]["Service"][];
        };
        ServiceResponse: {
            service: components["schemas"]["Service"];
        };
        /** @enum {string} */
        SubscriptionStatus: "active" | "pending" | "canceled" | "expired" | "suspended" | "none";
        /** @enum {string} */
        PaymentMethod: "paypal" | "manual";
        /** @enum {string} */
        ManualPaymentMethod: "cash" | "bank-transfer" | "other";
        UserServiceSubscription: {
            status: components["schemas"]["SubscriptionStatus"];
            paymentMethod: components["schemas"]["PaymentMethod"];
            paypalSubscriptionId?: string;
            paypalSubscriptionStatus?: string;
            /** Format: date-time */
            manualStartDate?: string;
            /** Format: date-time */
            manualEndDate?: string;
            manualTransactionId?: string;
            inGoogleGroup?: boolean;
            /** Format: date-time */
            activatedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateSubscriptionRequest: {
            /** @description Firebase user ID */
            uid: string;
            /** @description Service to subscribe to */
            serviceId: string;
        };
        CreateSubscriptionResponse: {
            /**
             * Format: uri
             * @description PayPal approval URL to redirect user
             */
            approvalUrl: string;
            /** @description PayPal subscription object */
            subscription?: Record<string, never>;
            subscriptionId: string;
        };
        ActivateSubscriptionRequest: {
            uid: string;
            /** @description PayPal subscription ID */
            subscriptionId: string;
        };
        ActivateSubscriptionResponse: {
            success: boolean;
            status: string;
            serviceId: string;
            subscription?: Record<string, never>;
        };
        PayPalWebhookEvent: {
            id?: string;
            /**
             * @example BILLING.SUBSCRIPTION.ACTIVATED
             * @example BILLING.SUBSCRIPTION.CANCELLED
             * @example BILLING.SUBSCRIPTION.EXPIRED
             * @example BILLING.SUBSCRIPTION.SUSPENDED
             */
            event_type?: string;
            resource?: {
                id?: string;
                status?: string;
                custom_id?: string;
            };
        };
        SubscriptionStatusResponse: {
            /** Format: email */
            email: string;
            services: {
                [key: string]: components["schemas"]["UserServiceSubscription"];
            };
        };
        AdminServiceRequest: {
            service: {
                /** @description If provided, updates existing service */
                id?: string;
                name?: string;
                nameHe?: string;
                description?: string;
                descriptionHe?: string;
                paypalPlanId?: string;
                pricePerMonth?: number;
                /** @enum {string} */
                currency?: "USD" | "ILS";
                /** Format: email */
                googleGroupEmail?: string;
                active?: boolean;
                order?: number;
                features?: string[];
                featuresHe?: string[];
            };
        };
        AdminServiceResponse: {
            success: boolean;
            message: string;
            serviceId: string;
        };
        ManualPaymentRequest: {
            /** Format: email */
            userEmail: string;
            serviceId: string;
            amount: number;
            durationMonths: number;
            paymentMethod: components["schemas"]["ManualPaymentMethod"];
            notes?: string;
            receiptNumber?: string;
            processedByUid: string;
            /** Format: email */
            processedByEmail: string;
        };
        ManualPaymentResponse: {
            success: boolean;
            message: string;
            transactionId: string;
            userId: string;
        };
        ManualTransaction: {
            id: string;
            userId: string;
            /** Format: email */
            userEmail: string;
            serviceId: string;
            serviceName: string;
            amount: number;
            currency: string;
            durationMonths: number;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
            notes?: string;
            paymentMethod: string;
            receiptNumber?: string;
            processedBy: string;
            /** Format: email */
            processedByEmail: string;
            /** Format: date-time */
            createdAt: string;
        };
        TransactionsResponse: {
            transactions: components["schemas"]["ManualTransaction"][];
        };
        CancelSubscriptionRequest: {
            uid: string;
            serviceId: string;
            reason?: string;
        };
        ManageGroupRequest: {
            uid: string;
            serviceId: string;
            /** @enum {string} */
            action: "add" | "remove";
        };
        MigrationResponse: {
            success: boolean;
            message: string;
            migrated: number;
            skipped: number;
            total: number;
        };
        SeedServicesResponse: {
            success: boolean;
            message: string;
            services: string[];
        };
        MediaItem: {
            /** @description Song/track title */
            title?: string;
            /** @description Artist name */
            artist?: string;
            /** @description Album name */
            album?: string;
        };
        TransliterateRequest: {
            /** @description Array of media items to transliterate (max 50) */
            items: components["schemas"]["MediaItem"][];
        };
        TransliteratedItem: {
            original?: components["schemas"]["MediaItem"];
            transliterated?: components["schemas"]["MediaItem"];
        };
        TransliterateResponse: {
            success: boolean;
            items: components["schemas"]["TransliteratedItem"][];
            /** @description Number of OpenAI tokens used */
            tokensUsed?: number;
        };
        SpotifyMetadataRequest: {
            /**
             * @description Spotify track URL (e.g., https://open.spotify.com/track/xxx or spotify:track:xxx)
             * @example https://open.spotify.com/track/5omHkj4qY0A8f6mE4T3fAH
             */
            spotifyUrl: string;
        };
        SpotifyMetadataResponse: {
            success: boolean;
            metadata: components["schemas"]["SpotifyTrackMetadata"];
        };
        SpotifyTrackMetadata: {
            /**
             * @description Spotify track ID
             * @example 5omHkj4qY0A8f6mE4T3fAH
             */
            trackId: string;
            /**
             * @description Track title
             * @example היה טוב
             */
            name: string;
            /**
             * @description Primary artist name
             * @example Omer Adam
             */
            artist: string;
            /**
             * @description Album name
             * @example תסמינים של פרידה
             */
            album: string;
            /**
             * @description International Standard Recording Code
             * @example IL1012501110
             */
            isrc: string;
            /**
             * @description Track duration in milliseconds
             * @example 213879
             */
            duration_ms: number;
            /**
             * @description Album release date (ISO format)
             * @example 2025-06-10
             */
            releaseDate?: string;
            /**
             * @description Album cover art URL
             * @example https://i.scdn.co/image/ab67616d0000b27312d961970aa13291d9720f8b
             */
            imageUrl?: string;
        };
        SpotifyAlbumMetadataRequest: {
            /**
             * @description Spotify album URL (e.g., https://open.spotify.com/album/xxx)
             * @example https://open.spotify.com/album/4fnlNjkYSlc6nmkNo5v9nC
             */
            spotifyUrl: string;
        };
        SpotifyAlbumMetadataResponse: {
            success: boolean;
            album: components["schemas"]["SpotifyAlbumInfo"];
            tracks: components["schemas"]["SpotifyAlbumTrack"][];
        };
        SpotifyAlbumInfo: {
            /**
             * @description Spotify album ID
             * @example 4fnlNjkYSlc6nmkNo5v9nC
             */
            albumId: string;
            /**
             * @description Album name
             * @example זמן להתעורר
             */
            name: string;
            /**
             * @description Primary artist name
             * @example Hadag Nahash
             */
            artist: string;
            /**
             * @description Album release date (ISO format)
             * @example 2013-03-20
             */
            releaseDate?: string;
            /**
             * @description Total number of tracks in album
             * @example 13
             */
            totalTracks: number;
            /**
             * @description Album cover art URL
             * @example https://i.scdn.co/image/ab67616d0000b273246dd456ad6730fb8a01c99a
             */
            imageUrl?: string;
        };
        SpotifyAlbumTrack: {
            /**
             * @description Spotify track ID
             * @example 7qhrpRjKIXTEIrzXOgQLbY
             */
            trackId: string;
            /**
             * @description Track position in album (1-based)
             * @example 1
             */
            position: number;
            /**
             * @description Track title
             * @example מסתובב
             */
            name: string;
            /**
             * @description Artist names (comma-separated if multiple)
             * @example Hadag Nahash
             */
            artists: string;
            /**
             * @description Album name
             * @example זמן להתעורר
             */
            album?: string;
            /**
             * @description International Standard Recording Code
             * @example IL4070900127
             */
            isrc: string;
            /**
             * @description Track duration in milliseconds
             * @example 56053
             */
            duration_ms: number;
            /**
             * @description Album cover art URL
             * @example https://i.scdn.co/image/ab67616d0000b273246dd456ad6730fb8a01c99a
             */
            imageUrl?: string;
            /**
             * @description Album release date
             * @example 2013-03-20
             */
            releaseDate?: string;
        };
        SpotifyPlaylistMetadataRequest: {
            /**
             * @description Spotify playlist URL (e.g., https://open.spotify.com/playlist/xxx)
             * @example https://open.spotify.com/playlist/4aneLdCay41fO9M1JYSTpq
             */
            spotifyUrl: string;
        };
        SpotifyPlaylistMetadataResponse: {
            success: boolean;
            playlist: components["schemas"]["SpotifyPlaylistInfo"];
            tracks: components["schemas"]["SpotifyPlaylistTrack"][];
        };
        SpotifyPlaylistInfo: {
            /**
             * @description Spotify playlist ID
             * @example 4aneLdCay41fO9M1JYSTpq
             */
            playlistId: string;
            /**
             * @description Playlist name
             * @example Assets
             */
            name: string;
            /**
             * @description Playlist owner/creator name
             * @example Noga scliar
             */
            owner: string;
            /**
             * @description Playlist description
             * @example My favorite tracks
             */
            description?: string;
            /**
             * @description Total number of tracks in playlist
             * @example 88
             */
            totalTracks: number;
            /**
             * @description Playlist cover image URL
             * @example https://mosaic.scdn.co/640/...
             */
            imageUrl?: string;
        };
        SpotifyPlaylistTrack: {
            /**
             * @description Spotify track ID
             * @example 7pdF27mSDuPWhppnHAmWHa
             */
            trackId: string;
            /**
             * @description Track position in playlist (1-based)
             * @example 1
             */
            position: number;
            /**
             * @description Track title
             * @example whoa (mind in awe)
             */
            name: string;
            /**
             * @description Artist names (comma-separated if multiple)
             * @example XXXTENTACION
             */
            artists: string;
            /**
             * @description Album name
             * @example SKINS
             */
            album: string;
            /**
             * @description International Standard Recording Code
             * @example USUYG1226220
             */
            isrc: string;
            /**
             * @description Track duration in milliseconds
             * @example 157776
             */
            duration_ms: number;
        };
        /**
         * @description Audio quality for Deezer downloads
         * @default MP3_320
         * @enum {string}
         */
        DeezerQuality: "MP3_128" | "MP3_320" | "FLAC";
        DeezerIsrcRequest: {
            /**
             * @description International Standard Recording Code
             * @example IL1012501118
             */
            isrc: string;
            quality?: components["schemas"]["DeezerQuality"];
        };
        DeezerDownloadUrlResponse: {
            /** @constant */
            success: true;
            /**
             * Format: uri
             * @description Direct download URL for the encrypted MP3/FLAC file
             * @example https://e-cdns-proxy-5.dzcdn.net/mobile/1/...
             */
            downloadUrl: string;
            quality: components["schemas"]["DeezerQuality"];
            /**
             * @description Blowfish decryption key (hex-encoded, derived from track ID)
             * @example a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6
             */
            decryptionKey: string;
        };
    };
    responses: {
        /** @description Bad request - missing or invalid parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Access denied - admin privileges required */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Service identifier (e.g., 'music-library', 'hasod-downloader') */
        ServiceIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getServices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active services */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicesResponse"];
                };
            };
        };
    };
    getService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Service identifier (e.g., 'music-library', 'hasod-downloader') */
                serviceId: components["parameters"]["ServiceIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Subscription created, approval URL returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSubscriptionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    activateSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Subscription activated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivateSubscriptionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    handlePaypalWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayPalWebhookEvent"];
            };
        };
        responses: {
            /** @description Webhook processed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Webhook processing failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSubscriptionStatus: {
        parameters: {
            query?: {
                /** @description User email (fallback if no Bearer token) */
                email?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User subscription status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatusResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createOrUpdateService: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminServiceRequest"];
            };
        };
        responses: {
            /** @description Service created/updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminServiceResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    deleteService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Service identifier (e.g., 'music-library', 'hasod-downloader') */
                serviceId: components["parameters"]["ServiceIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    processManualPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualPaymentRequest"];
            };
        };
        responses: {
            /** @description Payment processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualPaymentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAllTransactions: {
        parameters: {
            query?: {
                serviceId?: string;
                startDate?: string;
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionsResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getUserTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User's transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionsResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    adminCancelSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Subscription canceled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    manageGoogleGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManageGroupRequest"];
            };
        };
        responses: {
            /** @description Group membership updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    migrateUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Migration complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    seedServices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Services seeded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedServicesResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    transliterateMedia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransliterateRequest"];
            };
        };
        responses: {
            /** @description Transliteration successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransliterateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Subscription required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSpotifyMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpotifyMetadataRequest"];
            };
        };
        responses: {
            /** @description Metadata extracted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotifyMetadataResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Failed to extract metadata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSpotifyAlbumMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpotifyAlbumMetadataRequest"];
            };
        };
        responses: {
            /** @description Album metadata extracted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotifyAlbumMetadataResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Failed to extract album metadata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSpotifyPlaylistMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpotifyPlaylistMetadataRequest"];
            };
        };
        responses: {
            /** @description Playlist metadata extracted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotifyPlaylistMetadataResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Failed to extract playlist metadata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDeezerDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeezerIsrcRequest"];
            };
        };
        responses: {
            /** @description Download URL retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeezerDownloadUrlResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Subscription required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Track not found on Deezer */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Failed to retrieve download URL */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
